### ISSUE TITLE
tests hang during coverage

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/coverage#249]
With the package rxdart, I've bumped the SDK version for our builds from 2.0.0-dev to 2.2.0 stable, but now the build fails on collecting coverage:

The build first runs tests without coverage, which succeeds, using `pub run test test/rxdart_test.dart`

Then, it invokes the following:
- `pub global activate coverage`
- `pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates &`
- `dart --enable-vm-service=8111 --pause-isolates-on-exit test/rxdart_test.dart`
- `pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib`

...where it hangs indefinitely on `dart --enable-vm-service=8111 --pause-isolates-on-exit test/rxdart_test.dart`, as it seems `exit(0)` is never invoked.

The build ultimately fails after 10 minutes of being idle.

branch: https://github.com/ReactiveX/rxdart/tree/refactor/backpressure
build log: https://api.travis-ci.org/v3/job/505597822/log.txt

**Comment by fkorotkov** [comment]
Had the same issue and seems `nohup` helps:

```bash
nohup pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates &
```

**Comment by vitusortner** [comment]
I've got [`nohup`](https://github.com/vitusortner/floor/blob/68e7332cb12428a3c9a20f7a84d70eb24f2ca187/tool/travis.sh#L38) in place but Travis still fails after 10 minutes even though all tests passed. Do you have a clue why the coverage report is still failing on me?

Travis job log snippet:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by frankpepermans** [comment]
Our rxdart tests hang up with Dart 2.3, Dart 2.2 and below were running fine. (also using nohup without success).

Also looking for a way here to figure out why this is happening, any ideas?

**Comment by vanesyan** [comment]
Friendly cc @kevmoo @cbracken

**Comment by vanesyan** [comment]
I have fixed problem. The issue was that I didn't pass observatory port to `coverage:collect_coverage` so it wait forever.

**Comment by passsy** [comment]
This bug still exists in dart 2.4 and is blocking running code coverage on dart packages 
//cc @kevmoo @mit-mit @filiph

**Comment by MichaelMarner** [comment]
I ended up forcing Travis to use Dart 2.2 when running tests, as this hang does not seem to happen in Dart < 2.3

```yaml
language: dart
dart:
  - '2.2.0'
install:
  - gem install coveralls-lcov
script: ./tool/travis.sh
after_success:
  - coveralls-lcov var/lcov.info
env:
  - DARTANALYZER_FLAGS=--fatal-warnings
```

**Comment by fajarvm** [comment]
Has anyone got any solution for this? To force using Dart version 2.2 just to run code coverage is a bit odd. 

I'm using a similar set of commands as the original poster. The eyebrow-raising part is that there's little to no information on what causes the process to hang after running ```overage:collect_coverage```. It just wait forever.

**Comment by mit-mit** [comment]
Sorry about this issue, this slipped through the cracks as much of the team was out on vacation. But we are now aware of the issue, and will make sure to investigate the underlying cause (we have a few theories already).

**Comment by vsmenon** [comment]
@a-siva - you mentioned a VM change in this time frame?

**Comment by a-siva** [comment]
I believe this package needs to be updated to use the latest version of the coverage package.
It currently has the following entry in its pubspec.yaml file
  coverage: '>=0.11.0 <0.13.0'

A fix was made in 0.13.0 version to use --disable-service-auth-codes when invoking dart in travis.sh.

I verified this by invoking the sequence of commands posted in the original description:

- pub global activate coverage
- pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates &
- dart **--disable-service-auth-codes** --enable-vm-service=8111 --pause-isolates-on-exit test/rxdart_test.dart
- pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib

This sequence completes without any timeouts or hangs.

**Comment by mit-mit** [comment]
I left a comment in https://github.com/ReactiveX/rxdart/issues/287

**Comment by vsmenon** [comment]
Thanks!  Closing this for now as fixed.  Please comment / reopen if it still repros with the latest coverage.

fyi - @grouma

**Comment by frankpepermans** [comment]
@a-siva @mit-mit Thanks for your help!

The issue is indeed resolved by adding --disable-service-auth-codes in our case

**Comment by fajarvm** [comment]
Confirmed to be working for my project (latest Coverage lib, Dart version 2.4.0). Thanks a lot!
