### ISSUE TITLE
Ignoring via comments does not work at all

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [dart-lang/coverage#330]
Trying to exclude parts of a library from coverage with any of the comments will not work at all. Download the attached dart project [coverage_test.zip](https://github.com/dart-lang/coverage/files/5994405/coverage_test.zip) and run:
```.bash
$ dart test --coverage=coverage
$ dart run coverage:format_coverage --lcov --check-ignore \
		--in coverage \
		--out coverage/lcov.info \
		--packages .packages \
		--report-on lib
$ genhtml -o coverage/html coverage/lcov.info
```

The generated HTML will still contain all four test files will all lines. Nothing is ignored, even though all 3 variants have been tried out and `--check-ignore` was added to the command line.

**Comment by iapicca** [comment]
@pasindud any update on the [issue](https://github.com/flutter/flutter/pull/61408#issuecomment-757839556)

> Thanks @felix-barz-brickmakers, I'll have to take a look at this issue.

**Comment by pasindud** [comment]
So I think for non flutter stuff this commit should https://github.com/pasindud/coverage/commit/50fded8e59fa40713985ca166f404b92ca124a9b I'll have to test it bit more though


In the above example

```dart
class Foo<T> extends FooBase<T> {
  const Foo(T data)
      // coverage:ignore-line
      : super(data);

  T call() => data;
}
```


It should be 

```dart
class Foo<T> extends FooBase<T> {
  const Foo(T data)
      : super(data);        // coverage:ignore-line

  T call() => data;
}
```

**Comment by mark-revision** [comment]
After upgrading to Flutter 2.0/Dart 2.12.0 this feature works perfectly and correctly ignores untestable lines.

**Comment by grouma** [comment]
@iapicca what version of Flutter are you using? As @mark-revision stated, this should be working on the latest stable.

**Comment by iapicca** [comment]
@grouma 
the issue seems to persist running the same `code` and `test` provided [above](https://github.com/dart-lang/coverage/issues/330#issuecomment-795507589)

<details>
<summary>pubspec</summary>

```yaml
name: issue_330
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  flutter:
#    sdk: flutter


dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.16.7
```

</details>

<details>
<summary>logs</summary>

```bash
francesco@francesco-yoga720:~/projects/issue_330$ flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.203, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.203 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 4d1b2913fd (2 hours ago), 2021-03-10 21:05:02 -0500
    • Engine revision 4fd6bb1cdf
    • Dart version 2.13.0 (build 2.13.0-124.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.
francesco@francesco-yoga720:~/projects/issue_330$ format_coverage --lcov --check-ignore  --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
Can't load Kernel binary: Invalid kernel binary format version.
Precompiling executable... (1.8s)
Precompiled coverage:format_coverage.
francesco@francesco-yoga720:~/projects/issue_330$ genhtml -o coverage/html coverage/lcov.info
Reading data file coverage/lcov.info
Resolved relative source file path "lib/main.dart" with CWD to "/home/francesco/projects/issue_330/lib/main.dart".
Found 1 entries.
Found common filename prefix "/home/francesco/projects/issue_330"
Writing .css and .png files.
Generating output.
Processing file lib/main.dart
Writing directory view page.
Overall coverage rate:
  lines......: 75.0% (3 of 4 lines)
  functions..: no data found
francesco@francesco-yoga720:~/projects/issue_330$ cd coverage/html
francesco@francesco-yoga720:~/projects/issue_330/coverage/html$ chromium index.html

(chrome:385871): Gtk-WARNING **: 06:17:12.925: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name

(chrome:385871): Gtk-WARNING **: 06:17:12.929: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name

(chrome:385871): Gtk-WARNING **: 06:17:12.930: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
Opening in existing browser session.

```

</details>

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/110734967-8e756a00-8231-11eb-8d98-e4647a41c052.png)

</details>

**Comment by pasindud** [comment]
This is still showing that `// coverage:ignore-line` is in line 8 when it should be on line 9

**Comment by mark-revision** [comment]
Like @pasindud mentioned, you should put // coverage:ignore-line at the end of the line that you want to ignore, @iapicca and not above the line you want to ignore. Alternatively you can use start and end to ignore a block of code. Like mentioned [here](https://github.com/dart-lang/coverage/issues/162#issuecomment-456591358) 

// coverage:ignore-line: ignores the **current** line of code
// coverage:ignore-start: starts ignoring all next lines
// coverage:ignore-end: stops ignoring lines

ignore-line ignores the current, not next line of code, which makes sense with dart autoformatting.

**Comment by iapicca** [comment]
> This is still showing that `// coverage:ignore-line` is in line 8 when it should be on line 9

@pasindud 
my bad I thought this was is was meant to be implemented after your [commit](https://github.com/pasindud/coverage/commit/50fded8e59fa40713985ca166f404b92ca124a9b)
it does work indeed,
```dart
class FooBase<T> {
  final T data;
  const FooBase(this.data);
}

class Foo<T> extends FooBase<T> {
  const Foo(T data) : super(data); // coverage:ignore-line

  T call() => data;
}
```

[image](https://user-images.githubusercontent.com/45637986/110757114-b1187a80-8253-11eb-9cde-18feac33e611.png)

**Comment by grouma** [comment]
Closing this as working as intended.

**Comment by felix-barz-brickmakers** [comment]
It does not work for me yet. I am using dart 2.12.0, as distributed via the flutter SDK. Please, try again with the example I provided (but update  the min sdk to 2.12.0), without flutter. It does not work, not for any of the three ignore variants.

**Comment by iapicca** [comment]
@felix-barz-brickmakers 
maybe you are making my same mistake 
can you try like this
```dart
class UncoveredRange {
  String get test1 => 'test1'; // coverage:ignore-start

  void test2() {
    print('test2');
  } // coverage:ignore-start
}

```

**Comment by felix-barz-brickmakers** [comment]
@iapicca I tried all of these variants. None work - the screenshot was just one example. Here are some more:

<details>
<summary>Ignore file</summary>
![Ignore file](https://user-images.githubusercontent.com/60686992/110910607-e08dbc80-8311-11eb-9de8-6c2ffd1e4428.png)
</details>

<details>
<summary>Ignore range</summary>
![Ignore range](https://user-images.githubusercontent.com/60686992/110910797-1b8ff000-8312-11eb-84cd-aa6cb95aff52.png)
</details>

<details>
<summary>Ignore line</summary>
![Ignore line](https://user-images.githubusercontent.com/60686992/110910830-28144880-8312-11eb-8639-006694582a0b.png)
</details>

<details>
<summary>Dart version</summary>
```
Dart SDK version: 2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "windows_x64"
```
</details>

**Comment by felix-barz-brickmakers** [comment]
And one more: It works with flutter!

So, the following works correctly:
```
flutter test --coverage
```

But this does not:
```
dart test --coverage=coverage
dart run coverage:format_coverage --lcov --check-ignore \
		--in coverage \
		--out coverage/lcov.info \
		--packages .packages \
		--report-on lib
```

Maybe there is something wrong in how I call `coverage:format`? Or is there another way to generate lcov coverage from pure dart projects?

**Comment by abhaysood** [comment]
Facing similar issues with ignore coverage:https://github.com/flutter/flutter/issues/83425
